### ISSUE TITLE
PayU NetBanking

### ISSUE THREAD

**Issue by saanvaishnav** [payu-intrepos/Documentations#1]
PayU had created a dummy card for test app. What if some wants to test net-banking ? For each transaction PayU has record of merchantID. For testing purpose with test ID=key: gtKFFx Salt: eCwWELxi ,i used my SBI NET banking. That means there is no  merchant for the same transaction. Money goes to PayU guys. 
There should be a check on Test ID of dummy transaction for net Banking. 

Thank you. 
PS: Sbi transaction Ref No: IGOARWSKY8 .

**Comment by payuvalidate** [comment]
We always recommend our merchants to always test NB on their production key.
Still if by mistake a merchant transacts on test key with NB, they can ask for refund via the key account manager at PayU.

For any queries related to PayU's mobile SDK, please write to us at mobile-integration@payu.in
