### ISSUE TITLE
CB Integration issue IOS

### ISSUE THREAD

**Issue by chakradhar451** [payu-intrepos/Documentations#17]
(instancetype)initWithPostParam:(NSString*)postParam
                          url:(NSURL*)url
                     merchantKey:(NSString*)key
                                         error:(NSError**)error;

What should be the values of **postParam** and **url** in the above Method.

**Comment by vipin04** [comment]
It depends on the payment gateway you want to use.
For PayU PG, check the url/params format in sample app.

Value can be as follows for a Axis NB transaction. Most of the values given below will change from one merchant to another as well as from one end-user to another.

PostParam is a string
`@"instrument_id=12345678&instrument_type=iOS&device_type=2&key=gtKFFx&amount=10.00&productinfo=Nokia&firstname=Ram&email=email@testsdk1.com&txnid=pD22QuohoaKinvJ&surl=https://payu.herokuapp.com/success&furl=https://payu.herokuapp.com/failure&hash=9fe2e03be021df3869d57cf7e21a47a6b7ba06e5e16be3d98b921cb422e77326af986620c707eaad6d65c4591372c789f4af7d41ec61cb0aae0f9fdc21cc9e50&pg=NB&bankcode=AXIB&udf1=u1&udf2=u2&udf3=u3&udf4=u4&udf5=u5&user_credentials=ra:ra&phone=1111111111"
`

URL for production:
`https://secure.payu.in/_payment`
