### ISSUE TITLE
Stored Card dictionary missing in iOS.

### ISSUE THREAD

**Issue by KarthikMandava** [payu-intrepos/Documentations#19]
When I'm trying to pay using One Tap Payment, the error is coming like "**Stored Card dictionary missing**". Can you help me out from this.

**Comment by umangarya336** [comment]
Hi Karthik,
I think you have not set "OneTapTokenDictionary" which is key-value pair of “card_token” & “merchant_hash”.
Please refer to integration doc
https://github.com/payu-intrepos/Documentations/wiki/8.-iOS-SDK-integration#362-to-get-onetap-card

**Comment by KarthikMandava** [comment]
Thanks for response, I have set "OneTapTokenDictionary"  which is key-value pair of “card_token” & “merchant_hash”. Even it raises the same issue. But I am seeing while in payment process the post param is getting nil in  `self.createRequest = [PayUCreateRequest new];
    [self.createRequest createRequestWithPaymentParam:self.paymentParamForPassing forPaymentType:PAYMENT_PG_ONE_TAP_STOREDCARD withCompletionBlock:^(NSMutableURLRequest *request, NSString *postParam, NSString *error) {
    if (error == nil) {
      //It is good to go state. You can use request parameter in webview to open Payment Page
    }
    else{
      //Something went wrong with Parameter, error contains the error Message string
    }
}];`
