### ISSUE TITLE
libiOSCustomBrowser was built without full bitcode ?

### ISSUE THREAD

**Issue by BharathBob** [payu-intrepos/Documentations#25]
Hi there, 

I'm facing issue with libiOSCustomBrowser for bitcode enabled app, i cannot archive the app with this library integrated.

Here is the debugger message:
ld: bitcode bundle could not be generated because '/Users/Users/vishwabharath/TestApp/libiOSCustomBrowser.a(CBWSManager.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build file '/Users/vishwabharath/TestApp/libiOSCustomBrowser.a' for architecture armv7

Please help me out.

Thanks
Viswa

**Comment by vipin04** [comment]
Hi @BharathBob 
Please provide the information about the following tools to help you better:
1. The version of Xcode you are using
2. The version of iOS Custom Browser (CB) you are using
3. Integration of CB is done using Swift or Objective-C?

**Comment by BharathBob** [comment]
Xcode 9.2
Latest one downloaded from Git
Obj C

**Comment by BharathBob** [comment]
Any update?

**Comment by vipin04** [comment]
Hey @BharathBob,

I am sorry, I really could not devote time to investigate the issue further. The issue existed earlier but it was fixed, I guess, about a year ago.
I request you to replicate this issue with our sample app. Use the same version of CB in our sample app, that you are using in your app. 
As the sample app is also in Obj-C, this should give a fair idea if the issue got re-introduced in CB.

**Comment by vipin04** [comment]
Hi @BharathBob 

I tried exporting the sample app with latest CB integrated and export was successful.
I request you to try that out.
If you are still stuck, please get in touch at mobile.integration@payu.in
