### ISSUE TITLE
Cannot verify Bank's VAS Status.

### ISSUE THREAD

**Issue by anmolmalhotra** [payu-intrepos/Documentations#28]
Hi there,

I am trying to verify if bank is open or not by calling function
```
let webService = PayUWebService()

webService.callVAS(paymentParamsforVas: paymentParams)

webService.getVASStatus(bankCodeOrCardBin: paymentParams.bankCode)...
```

The response from this call always gives me **Invalid card bin or bank code**.

I am sure I am not sending the wrong bank code. I have tried with `AXIB`, `HDFB`, `BOIB`, `CABB`. How come it can throw error for all these bank codes? They're valid, right? Can you please give me more context about this error? Why this is happening?

**Comment by AshishPayU** [comment]
Hi Anmol,

Please drop email at mobile.integration@payu.in
with some sample code.

Thanks,
Ashish

**Comment by anmolmalhotra** [comment]
Unfortunately, I cannot share the code. Can you please check this on your behalf?

**Comment by vivektakrani** [comment]
Hello Anmol,
I am facing the same issue. Were you able to resolve it?
