### ISSUE TITLE
NetBanking

### ISSUE THREAD

**Issue by Tamil-Vendhan** [payu-intrepos/Documentations#33]
On non-seamless - through NetBanking, notification observer is not called for success or failure of transaction and getting stuck on PUCBWebVC. But notification observer is getting data through card payment or payumoney.

**Comment by vipin04** [comment]
Hello,

Did you try NB option on the [sample app](https://github.com/payu-intrepos/iOS-SDK-Sample-App)?
I tried and the response comes in it.
Please check once.

**Comment by Tamil-Vendhan** [comment]
Hi,

I have checked the sample app.  The issue was on surl and furl which was not a proper url given from my end. Now working perfectly. Thank you for the quick response @vipin04
