### ISSUE TITLE
How to use PayU SDK  with Eclipse ?

### ISSUE THREAD

**Issue by afixi-bibhu** [payu-intrepos/Documentations#4]
How to import PayU Sdk to eclipse.
Provide a sample app in which PayU SDK is used which can be imported to Eclipse.

**Comment by Shruti6293** [comment]
You can take .aar file from studio version and rename it with .zip file.
Extract that zip file and Find the classes.jar file in the extracted files.
Create new library project without any activity .Put classes.jar file in lib folder.
And copy all res file and link that library project to your main app.
It will work.

**Comment by payuvalidate** [comment]
Please write to us at mobile-integration@payu.in and we can assist you accordingly.
