### ISSUE TITLE
Links for reference android/ios surl and furl are dead.

### ISSUE THREAD

**Issue by binaryKarmic** [payu-intrepos/Documentations#6]
The reference links given on the page [https://github.com/payu-intrepos/Documentations/wiki/4.-Server-Side#return-url---surl--furl](url) are dead.

android surl and furl
https://payu.herokuapp.com/success
https://payu.herokuapp.com/failure

iOS surl and furl
https://payu.herokuapp.com/ios_success
https://payu.herokuapp.com/ios_failure

The sample code is not helping much. The client side implementation asks for 2 urls 
`mPaymentParams.setSurl(“https://payu.herokuapp.com/success”);
mPaymentParams.setFurl(“https://payu.herokuapp.com/failure");` 

refe : [https://github.com/payu-intrepos/Documentations/wiki/6.-Android-SDK-Integration#21-non-seamless-using-sdks-inbuilt-ui](url)

Whereas the sample code given on link [https://github.com/payu-intrepos/Documentations/wiki/4.-Server-Side#return-url---surl--furl](url)
shows only one page with both PayU.onSuccess(input); and PayU.onFailure(input); calls.

The links for reference was our hope to solve this but they too are dead links.

**Comment by payuvalidate** [comment]
Please use the latest SDK and for any queries related to PayU's mobile SDK, please write to us at mobile-integration@payu.in
