### ISSUE TITLE
PayU hash key

### ISSUE THREAD

**Issue by beyondkeysystem** [payu-intrepos/Documentations#7]
Hi 
We are successfully integrated payU sdk, and it is working with sample app with test credential, but while we are using production enviroment and generated hash key for php server and using it in mobile sdk it throwing invalid hash key, I go thorough code and see that payment_related_details_for_mobile_sdk has should be pass, so what we have to do for get payment_related_details_for_mobile_sdk hash key

**Comment by Balasnest** [comment]
Facing this same issue. message = "Could not generate hash for .... , please try with any one payu test credentials". How could I solve this?

**Comment by Balasnest** [comment]
Hi @beyondkeysystem I am facing same problem , can you please provide the solution of this issue

**Comment by payuvalidate** [comment]
Everyone, please write to us at mobile-integration@payu.in and we can help you with such issues.
