### ISSUE TITLE
problem in non seamless ios app

### ISSUE THREAD

**Issue by kunalprsd2** [payu-intrepos/Documentations#8]
i have passed all data in 

 PUUIPaymentOptionVC *paymentOptionVC = [stryBrd instantiateViewControllerWithIdentifier:VC_IDENTIFIER_PAYMENT_OPTION];

```
        NSLog(@"checking data  ");
        paymentOptionVC.paymentParam = self.paymentParam;
        paymentOptionVC.paymentRelatedDetail = paymentRelatedDetails;
```

[self.navigationController pushViewController:paymentOptionVC animated:true];

new story board get launch but when click on  pay now then its creating problem and hanged.
and show this bug.

-[OS_dispatch_data gunzippedData]: unrecognized selector sent to instance 0x12664d670
2016-08-11 13:17:32.999 SamplePayu[329:22640] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[OS_dispatch_data gunzippedData]: unrecognized selector sent to instance 0x12664d670'
**\* First throw call stack:
(0x182b12db0 0x182177f80 0x182b19c4c 0x182b16bec 0x182a14c5c 0x10010ef78 0x10010e34c 0x10023da7c 0x10023da3c 0x1002434e4 0x182ac8d50 0x182ac6bb8 0x1829f0c50 0x1842d8088 0x187cda088 0x100101bf0 0x18258e8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by chaitanyapottam** [comment]
i too facing the same exception. Don't understand how to address this issue. My main application is of Swift. PayU dev team should help.

**Comment by chaitanyapottam** [comment]
i have resolved the problem. Hurryyyyy .... in my case i have missed to include -ObjC linker flag to the sample. Once i included that now the project is working.

try this following link. Check the step 2. Step 2 describes how to include -ObjC linker file to the project.

Hope this will help you.

**Comment by payuvalidate** [comment]
Thanks for the update. Please write to us at mobile-integration@payu.in so we can timely assist you in future.

**Comment by bacancyhima** [comment]
I have added -ObjC in other linker flags, but app is still getting crash on PayNow button. Will you pls help for the same. Getting same exception of -[OS_dispatch_data gunzippedData]: unrecognized selector sent to instance

**Comment by vipin04** [comment]
Hi,

Following changes are required in your apps' project settings as pre-req to integrate Custom Browser.

1. Add **libz.tbd** libraries into your project target's Build Phases->Link Binary with Libraries.
2. Add **-ObjC** in Other Linker Flags in Project Build Settings.
3. Add **SystemConfiguration** framework into your project target's Build Phases->Link Binary with Libraries

Try them, if app still crashes, let us know.

**Comment by bacancyhima** [comment]
Hi, 

I have followed all these 3 steps, but it is still crashing,
1. If I am choosing any bank from Net Banking option
2. I am choosing PAY NOW from PayUMoney.

In Both the case, app will get crashed, in gives exception of -[OS_dispatch_data gunzippedData]:

Thank you.

**Comment by vipin04** [comment]
Please write to mobile-integration@payu.in to get assistance from integrations team.

**Comment by umangarya336** [comment]
Try adding **$(OTHER_LDFLAGS)** & -**ObjC** both in Other Linker Flags in Project Build Settings. If issue still persist then please write to above given mail ID for further assistance.

**Comment by bacancyhima** [comment]
Hi, 

Still same crashing issue.. I don't know about merchant key. I haven't added it. Is it because of that?
I have seen an example from internet.. and I have implemented the code just like that.

**Comment by shankar101** [comment]
Thank you so much other linker flags (-ObjC) that's work for me.
